name: xprize-final
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel>=6.0.0
  - ipython>=8.0.0
  - jupyter
  - pip>=23.0.0
  - python=3.11.0
  - scikit-learn>=1.2.0
  - seaborn>=0.11.0
  - spyder-kernels>=0.2.0
  - tqdm
  - librosa
  - umap-learn
  - pip:
      - scikit-maad>=1.4.2
      - kneed
      - hdbscan
  
